import Phaser from 'phaser';
import * as PlayerData from '../data/PlayerData';

import {
  GAUNTLET_GROUPS,
  GAUNTLET_ELEMENTS,
  GauntletState,
  GAUNTLET_DIFFICULTY,
  GAUNTLET_HARD_DIFFICULTY,
  INFINITY_GAUNTLET_ID,
  emptyRunBoosts,
} from '../data/GauntletData';
import { MUTATIONS, getBossMutationIds } from '../data/Mutations';
import {
  C, addBackdrop, addBackButton, addTitle, ElementPanels, openBondPicker, renderElementGrid,
} from '../ui';
import { Music } from '../audio';

const GAUNTLET_EXCLUDED_MUTATIONS = new Set(['boss', 'raid']);

export class GauntletElementSelectScene extends Phaser.Scene {
  /** Set once the bond modal has answered, so re-entry does not reopen it. */
  private bondChosen = false;
  private gauntletId = 'fire';
  private hardMode = false;
  private elemPage = 0;
  private phaseObjects: Phaser.GameObjects.GameObject[] = [];
  /** The info / mastery / customize overlays, identical to the main menu's. */
  private panels!: ElementPanels;
  /** Pager tint: gold for a normal run, corrupt for hard mode. */
  private accent = C.gold;

  constructor() {
    super({ key: 'GauntletElementSelectScene' });
  }

  init(data: { gauntletId: string; hardMode?: boolean }): void {
    this.gauntletId = data.gauntletId;
    this.hardMode = data.hardMode ?? false;
    this.elemPage = 0;
    this.phaseObjects = [];
  }

  create(): void {
    Music.play('gauntlet');
    const cx = this.scale.width / 2;

    const accent = this.hardMode ? C.corrupt : C.gold;
    addBackdrop(this, { accent, variant: 'lattice', motes: 18 });

    const gauntletEl = GAUNTLET_ELEMENTS.find((e) => e.id === this.gauntletId);
    const modeTag = this.hardMode ? '   🔥 HARD MODE' : '';
    const battleCount = this.hardMode ? '7' : '5';
    const isInfinity = this.gauntletId === INFINITY_GAUNTLET_ID;
    const label = isInfinity
      ? `∞ INFINITY GAUNTLET${modeTag}  ·  ENDLESS — FIGHT UNTIL YOU DIE`
      : gauntletEl
      ? `${gauntletEl.emoji} ${gauntletEl.name.toUpperCase()} GAUNTLET${modeTag}  ·  ${battleCount} BATTLES + A BOSS`
      : 'GAUNTLET';

    addTitle(this, {
      x: cx, y: 62, text: 'CHOOSE YOUR ELEMENT', accent, size: 34,
      subtitle: label,
    });

    this.panels = new ElementPanels(this, () => this.renderElements());
    this.accent = accent;

    const back = () => {
      if (this.panels.isOpen()) this.panels.closeElementInfo();
      else this.scene.start('GauntletSelectScene');
    };
    addBackButton(this, back);
    this.input.keyboard!.on('keydown-ESC', back);

    this.renderElements();
  }

  private renderElements(): void {
    for (const obj of this.phaseObjects) {
      if (obj.active) (obj as Phaser.GameObjects.GameObject & { destroy(): void }).destroy();
    }
    this.phaseObjects = renderElementGrid(this, {
      y: this.scale.height / 2 + 20,
      page: this.elemPage,
      panels: this.panels,
      accent: this.accent,
      onPageChange: (pg) => { this.elemPage = pg; this.renderElements(); },
      onSelect: (id) => this.selectElement(id),
      emptyText: 'No extra elements unlocked yet.\nVisit the LAB to unlock combined elements.',
    });
  }

  private selectElement(elementId: string): void {
    // Same gate as the campaign and the main menu: Quantum needs its pair before launch.
    if (elementId === 'quantum' && !this.bondChosen) {
      openBondPicker(this, (a, b) => {
        PlayerData.setQuantumBond(a, b);
        this.bondChosen = true;
        this.selectElement(elementId);
      });
      return;
    }
    if (this.gauntletId === INFINITY_GAUNTLET_ID) {
      // Infinity: first fight is generated by GauntletIntermediaryScene's launchInfinityFight.
      // We start with fight 0 "complete" so the intermediary scene generates fight 1.
      const gauntlet: GauntletState = {
        gauntletElement: INFINITY_GAUNTLET_ID,
        playerElement: elementId,
        currentFight: 0,
        boosts: emptyRunBoosts(),
        fightOrder: [],
        fightMutations: [],
        hardMode: this.hardMode,
        infinityShards: 0,
      };
      // Go straight to intermediary which will generate and launch fight 1
      this.scene.start('GauntletIntermediaryScene', { gauntlet });
      return;
    }

    const pool = GAUNTLET_GROUPS[this.gauntletId] ?? [];
    const allowedMutations = MUTATIONS
      .filter((m) => !GAUNTLET_EXCLUDED_MUTATIONS.has(m.id) && !m.bossOnly)
      .map((m) => m.id);

    const pickN = (n: number): string[] => {
      const bag = [...allowedMutations].sort(() => Math.random() - 0.5);
      return bag.slice(0, Math.min(n, bag.length));
    };

    const bossIds = getBossMutationIds();
    const bossId = bossIds[Math.floor(Math.random() * bossIds.length)];

    let fightOrder: string[];
    let fightMutations: string[][];
    let difficulty0: number;
    let mutations0: string[];

    if (this.hardMode) {
      const shuffled = [...pool].sort(() => Math.random() - 0.5);
      fightOrder = Array.from({ length: 7 }, (_, i) => shuffled[i % shuffled.length]);
      const regularMutations = Array.from({ length: 7 }, () => pickN(1));
      const bossSlot = [bossId, ...pickN(1)];
      fightMutations = [...regularMutations, bossSlot];
      difficulty0 = GAUNTLET_HARD_DIFFICULTY[0];
      mutations0 = fightMutations[0];
    } else {
      fightOrder = [...pool].sort(() => Math.random() - 0.5);
      const regularMutations = Array.from({ length: 5 }, () => pickN(1));
      fightMutations = [...regularMutations, [bossId]];
      difficulty0 = GAUNTLET_DIFFICULTY[0];
      mutations0 = fightMutations[0];
    }

    const gauntlet: GauntletState = {
      gauntletElement: this.gauntletId,
      playerElement: elementId,
      currentFight: 1,
      boosts: emptyRunBoosts(),
      fightOrder,
      fightMutations,
      hardMode: this.hardMode,
      infinityShards: 0,
    };

    this.scene.start('ArenaScene', {
      elementId,
      enemyElementId: fightOrder[0],
      difficulty: difficulty0,
      mutations: mutations0,
      gauntlet,
      playerPerk: PlayerData.getEquippedPerk(elementId),
    });
  }
}
